// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcfTR8fKzuZrpusCA11U0r6KqZgC-sZX0',
    appId: '1:738623587191:web:86efb0153172adf6ded772',
    messagingSenderId: '738623587191',
    projectId: 'info6350-f0055',
    authDomain: 'info6350-f0055.firebaseapp.com',
    storageBucket: 'info6350-f0055.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9AohaHzf2z18C_YEFY-ZJV38k133UixU',
    appId: '1:738623587191:android:bc835cfd09afb0ccded772',
    messagingSenderId: '738623587191',
    projectId: 'info6350-f0055',
    storageBucket: 'info6350-f0055.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr-Wsk3ATQKeYfDYo5y18naQh1niX7a_I',
    appId: '1:738623587191:ios:01c53272a201f036ded772',
    messagingSenderId: '738623587191',
    projectId: 'info6350-f0055',
    storageBucket: 'info6350-f0055.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr-Wsk3ATQKeYfDYo5y18naQh1niX7a_I',
    appId: '1:738623587191:ios:85f35ebe79f0e0f7ded772',
    messagingSenderId: '738623587191',
    projectId: 'info6350-f0055',
    storageBucket: 'info6350-f0055.appspot.com',
    iosBundleId: 'com.example.finalProject.RunnerTests',
  );
}
